### ISSUE TITLE
issue: Date should be rounder when added days 

### ISSUE THREAD

**Issue by rishabhjainfinal** [kuzmoyev/beautiful-date#16]
```python
today = D.today()
print(today)
print(today + 5*day )
```
```
results
2021-08-29
2021-08-05 # should be 2021-09-05
```

### Just a humble request to implement this if possible.

**Comment by kuzmoyev** [comment]
You need to use `days` instead of `day`. `day` sets the date while `days` adds it. See [this](https://github.com/kuzmoyev/beautiful-date#datedatetime-manipulations) for more details.

**Comment by rishabhjainfinal** [comment]
> You need to use `days` instead of `day`. `day` sets the date while `days` adds it. See [this](https://github.com/kuzmoyev/beautiful-date#datedatetime-manipulations) for more details.

thanks for quick reply and exact sol
